// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBp-YkPQ4HG41K2T_VOQdk1pQaJx-B7Rk0',
//     appId: '1:1031540201259:web:6f3cee1d511b7b8f4f976e',
//     messagingSenderId: '1031540201259',
//     projectId: 'yes-yes-loyalty',
//     authDomain: 'yes-yes-loyalty.firebaseapp.com',
//     storageBucket: 'yes-yes-loyalty.appspot.com',
//     measurementId: 'G-72GVKPLM79',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyClZnv4kCznedqU3O7osM4S0SS54LjLQes',
//     appId: '1:1031540201259:android:459467725663edcd4f976e',
//     messagingSenderId: '1031540201259',
//     projectId: 'yes-yes-loyalty',
//     storageBucket: 'yes-yes-loyalty.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAiCfgdgLnColQf7twmdTgZF5l7Rd8gFXE',
//     appId: '1:1031540201259:ios:79ebb4bcb8b69b0a4f976e',
//     messagingSenderId: '1031540201259',
//     projectId: 'yes-yes-loyalty',
//     storageBucket: 'yes-yes-loyalty.appspot.com',
//     iosBundleId: 'com.yesyesloyalty.app',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAiCfgdgLnColQf7twmdTgZF5l7Rd8gFXE',
//     appId: '1:1031540201259:ios:79ebb4bcb8b69b0a4f976e',
//     messagingSenderId: '1031540201259',
//     projectId: 'yes-yes-loyalty',
//     storageBucket: 'yes-yes-loyalty.appspot.com',
//     iosBundleId: 'com.yesyesloyalty.app',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBp-YkPQ4HG41K2T_VOQdk1pQaJx-B7Rk0',
//     appId: '1:1031540201259:web:d0754e1d7bb5a8414f976e',
//     messagingSenderId: '1031540201259',
//     projectId: 'yes-yes-loyalty',
//     authDomain: 'yes-yes-loyalty.firebaseapp.com',
//     storageBucket: 'yes-yes-loyalty.appspot.com',
//     measurementId: 'G-KD5RQ9Z2RC',
//   );
// }
